### ISSUE TITLE
[Feature Request] Pre-compiled binary for aarch64

### ISSUE THREAD

**Issue by 4513ECHO** [high-moctane/mocword#6]
Nextword have release for aarch64(arm64), but mocword doesn't. How about add suport?

**Comment by high-moctane** [comment]
Ok I'll prepare aarch64 builds in the next version (｀･ω･´)

**Comment by high-moctane** [comment]
@4513ECHO I just added aarch64 (Linux, macOS) release support. Could you check it at https://github.com/high-moctane/mocword/releases/tag/v0.2.0 ?

**Comment by 4513ECHO** [comment]
I tried in Raspberry Pi (Ubuntu, aarch64):

```console
$ mocword --version
mocword 0.2.0
```

It works correctly. Thanks!
